services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=https://doku.borinas.com
      - APP_KEY=base64:3qjlIoUX4Tw6fUQgZcxMbz6lb8+dAzqpvItqHvahW1c=
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bookstack     # muss mit MYSQL_DATABASE im MariaDB-Container übereinstimmen
      - DB_USERNAME=bookstack     # muss mit MYSQL_USER im MariaDB-Container übereinstimmen
      - DB_PASSWORD=bookstack8432 # muss mit MYSQL_PASSWORD im MariaDB-Container übereinstimmen
    volumes:
      - /docker/appdata/bookstack/bookstack_app_data:/config
    ports:
      - 6875:80 
    restart: unless-stopped

  # Datenbankcontainer für BookStack
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_DATABASE=bookstack      # muss mit DB_DATABASE im BookStack-Container übereinstimmen
      - MYSQL_USER=bookstack          # muss mit DB_USERNAME im BookStack-Container übereinstimmen
      - MYSQL_PASSWORD=bookstack8432  # muss mit DB_PASSWORD im BookStack-Container übereinstimmen
      - MYSQL_ROOT_PASSWORD=mysupersecretrootpassword 
    volumes:
      - /docker/appdata/bookstack/bookstack_db_data:/config
    restart: unless-stopped
