services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
      - ./release:/data/release
    restart: unless-stopped

# Optional
volumes:
  npm_data:
    external: true
    name: nginx-proxy-manager_data
  npm_letsencrypt:
    external: true
    name: nginx-proxy-manager_letsencrypt
